### ISSUE TITLE
Property 'json' does not exist on type 'ObjectDefinitionBlock<"MyModel"> (issue with custom Scalars)

### ISSUE THREAD

**Issue by kunovsky** [graphql-nexus/nexus-plugin-prisma#1007]
Hi There,

I've spent the last couple of days migrating off of the nexus framework onto `nexus` + `nexus-plugin-prisma` + `apollo-server-express`. Apologies if this is not applicable to `nexus-plugin-prisma` and is instead applicable to `nexus` but I'm guessing it might be because when I try and run my app I'm getting this error:

`Property 'json' does not exist on type 'ObjectDefinitionBlock<"MyModel">`

After following this [guide for Nexus Framework Users](https://nexusjs.org/docs/adoption-guides/nexus-framework-users) and this [guide for Nexus Framework Prisma Users](https://nexusjs.org/docs/adoption-guides/neuxs-framework-prisma-users) I've got the app running everything except for Scalars working and was wondering what I'm doing wrong to cause this error, or if this is potentially an error on the `nexus-plugin-prisma` side of things. For context, here is my setup:

`package.json`
```js
{
  "name": "myapp",
  "version": "0.0.1",
  "license": "MIT",
  "scripts": {
    "build": "yarn nexus:reflect && rimraf dist && tsc",
    "dev": "ts-node-dev --transpile-only ./api/app.ts",
    "dev:typecheck": "tsc --noEmit --watch",
    "nexus:reflect": "ts-node ./api/schema.ts",
    "reset": "dropdb myDb && npx prisma generate && npx prisma migrate dev --preview-feature && npm run seed",
  },
  "dependencies": {
    "@prisma/client": "^2.13.1",
    "apollo-server-express": "^2.19.0",
    "express": "^4.17.1",
    "graphql": "^15.4.0",
    "graphql-scalars": "^1.6.1",
    "nexus": "^1.0.0",
    "nexus-plugin-prisma": "0.27.0"
  },
  "devDependencies": {
    "@prisma/cli": "^2.13.1"
  }
}
```

`.env`
```js
NODE_ENV=production
```

`tsconfig.json`

```js
{
  "compilerOptions": {
    "rootDir": ".",
    "target": "es5",
    "moduleResolution": "node",
    "module": "commonjs",
    "sourceMap": true,
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "lib": ["esnext", "dom"],
    "noEmit": true,
    "noEmitHelpers": true,
    "importHelpers": true,
  }
}
```

`schema.ts`
```js
import * as path from 'path'

import { makeSchema } from 'nexus'
import { GraphQLScalarType } from 'graphql'

import { DateTimeResolver, JSONObjectResolver } from 'graphql-scalars'

import { nexusPrisma } from 'nexus-plugin-prisma'

import * as types from './graphql'

export default makeSchema({
  contextType: {
    module: path.join(__dirname, 'context.ts'),
    export: 'Context'
  },
  sourceTypes: {
    modules: [
      {
        module: require.resolve('../node_modules/@prisma/client/index.d.ts'),
        alias: 'prisma'
      }
    ]
  },
  plugins: [
    nexusPrisma({
      experimentalCRUD: true,
      scalars: {
        date: DateTimeResolver,
        json: new GraphQLScalarType({
          ...JSONObjectResolver,
          name: 'json',
          description:
            'The `JSON` scalar type represents JSON objects as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).'
        })
      }
    })
  ],
  types
})

```

my types in the `graphql` dir (`index.ts`):

```js
// Export All Types
export * from './MyModel'
... all the rest of my types
```

`MyModel.ts`
```js
import { objectType } from 'nexus'

export const MyModel = objectType({
  name: 'MyModel',
  definition(t) {
    t.string('id')
    t.string('version')
    t.string('createdAt')
    t.json('someField') // <- Property 'json' does not exist on type 'ObjectDefinitionBlock<"MyModel">
  }
})
```

Note that if I try `t.field('someField', { type: 'json' })` this also fails.

I'm currently running `npx prisma generate` to generate the client which works fine. And then when I try to run either of the following npm scripts: `"nexus:reflect": "ts-node ./api/schema.ts",` or `"dev": "ts-node-dev --transpile-only ./api/app.ts"` i'm getting:

```
 Property 'json' does not exist on type 'ObjectDefinitionBlock<"MyModel">'.

9     t.json('versionData')
        ~~~~
    at createTSError (/Users/foo/Desktop/bar/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/Users/foo/Desktop/bar/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/Users/foo/Desktop/bar/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/Users/foo/Desktop/bar/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/Users/foo/Desktop/bar/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/foo/Desktop/bar/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
```

Again apologies if this is just me doing something goofy, I just can't figure out for the life of me what I'm doing wrong here. I do notice that there is a difference between the two guides for how to set up Scalars: [guide for Nexus Framework Users](https://nexusjs.org/docs/adoption-guides/nexus-framework-users#bundled-scalars) vs [guide for Nexus Framework Prisma Users](https://nexusjs.org/docs/adoption-guides/neuxs-framework-prisma-users#configuring-custom-scalars) but I've tried both approaches and neither seem to work. Please let me know if you require more info on logs or setup, and thanks!

**Comment by kunovsky** [comment]
I've not solved this quite yet but as was recommended on the Prisma slack, in my `schema.ts` I moved my scalars away from this configuration:
my old `schema.ts`
```js
  plugins: [
    nexusPrisma({
      experimentalCRUD: true,
      scalars: {
        date: DateTimeResolver,
        json: new GraphQLScalarType({
          ...JSONObjectResolver,
          name: 'json',
          description:
            'The `JSON` scalar type represents JSON objects as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).'
        })
      }
    })
  ],
```

and instead, have a `Scalar.ts` file now where I'm configuring my Json and Date scalar and then importing them as I do all my other types:
`Scalar.ts`
```js
import { asNexusMethod } from 'nexus'

import { DateTimeResolver, JSONObjectResolver } from 'graphql-scalars'

export const JsonScalar = asNexusMethod(JSONObjectResolver, 'json')
export const DateTimeScalar = asNexusMethod(DateTimeResolver, 'date')
```
my new `schema.ts`
```js
import * as path from 'path'

import { makeSchema } from 'nexus'

import { nexusPrisma } from 'nexus-plugin-prisma'

import * as types from './graphql'

export default makeSchema({
  contextType: {
    module: path.join(__dirname, 'context.ts'),
    export: 'Context',
    alias: 'ctx'
  },
  sourceTypes: {
    modules: [
      {
        module: require.resolve('.prisma/client/index.d.ts'),
        alias: 'prisma'
      }
    ]
  },
  plugins: [
    nexusPrisma({
      experimentalCRUD: true
    })
  ],
  types,
  outputs: {
    typegen: path.join(__dirname, 'index.d.ts'),
    schema: path.join(__dirname, 'schema.graphql')
  }
})
```

in my `schema.graphql` I have:

```js
"""
The `JSONObject` scalar type represents JSON objects as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
"""
scalar JSONObject

"""
A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
"""
scalar DateTime
```

and in my `index.d.ts` I have:

```js
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * The `JSONObject` scalar type represents JSON objects as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
     */
    json<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "JSONObject";
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    date<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * The `JSONObject` scalar type represents JSON objects as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
     */
    json<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "JSONObject";
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
  }
}
```

I now can see that I can use the `.` accessor to add a `t.date` or `t.json` to my `objectTypes`:
![image](https://user-images.githubusercontent.com/4792753/103096520-2d46de80-45d2-11eb-9d28-e25fcd658be7.png)

BUT... when I try and run `"ts-node ./api/schema.ts"` I'm still getting the same error:

`Property 'date' does not exist on type 'ObjectDefinitionBlock<"MyModel">'.`

**Comment by kunovsky** [comment]
Alright, I've finally got it working, and looks like this was my bad and not a bug as the issue was due to an improperly configured `tsconfig.json`. For anyone else who encounters this issue here is my updated `tsconfig.json`:

```js
{
  "compilerOptions": {
    "sourceMap": true,
    "module": "CommonJS",
    "target": "ES2017",
    "moduleResolution": "node",
    "outDir": "dist",
    "strict": true,
    "lib": ["esnext"],
    "esModuleInterop": true,
    "noUnusedLocals": true,
    "skipLibCheck": true
  },
  "include": ["api"]
}
```
I'm going to close this issue now.
