### ISSUE TITLE
Enums generated by Prisma Client Throw Errors

### ISSUE THREAD

**Issue by fullStackDataSolutions** [graphql-nexus/nexus-plugin-prisma#1022]
I did prisma introspect, with:
```
datasource deliverables {
  provider = "mysql"
  url      = env("DATABASE_URL")
}
```
I got the following Schema:

```
model ftp_profile {
  ftp_profile_id  Int                          @id @default(autoincrement())
  description     String
  server_protocol ftp_profile_server_protocol
  ...
}

enum ftp_profile_server_protocol {
  FTP
  SFTP
  FTPS
}
```

Then run Prisma generate with the below set:

```
generator client_deliverables {
  provider = "prisma-client-js"
  output   = "../../src/generated/prisma/ftp/client"
}

```

I then created the types with nexus:

```

export const serverProtocol = enumType({ 
    name: "ftp_profile_server_protocol",
    description: 'FTP server protocal values FTP, SFTP, FTPS',
    members: ["FTP", "SFTP", "FTPS" ]
});


export const ftpProfile = objectType({
    name: TypeName,
    description:
        '',
    definition(t) {
        t.model.ftp_profile_id({ alias: 'id' });
        t.model.description();
        t.model.server_protocol();
        ...
    }
});
```

When I try to execute :

{
  ftpProfiles(first:10){
    id
  }
}

I get the following error:

```

{
  "errors": [
    {
      "message": "\nInvalid `prisma.ftp_profile.findMany()` invocation:\n\n\n  Value '' not found in enum 'DatabaseEnumType { name: \"server_protocol\", internal_enum: InternalEnum { name: \"server_protocol\", values: [InternalEnumValue { name: \"FTP\", database_name: None }, InternalEnumValue { name: \"SFTP\", database_name: None }, InternalEnumValue { name: \"FTPS\", database_name: None }] } }'",
      "locations": [],
      "path": [
        "ftpProfiles"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "clientVersion": "2.14.0",
          "stacktrace": [
            "Error: ",
            "Invalid `prisma.ftp_profile.findMany()` invocation:",
            "",
            "",
            "  Value '' not found in enum 'DatabaseEnumType { name: \"server_protocol\", internal_enum: InternalEnum { name: \"server_protocol\", values: [InternalEnumValue { name: \"FTP\", database_name: None }, InternalEnumValue { name: \"SFTP\", database_name: None }, InternalEnumValue { name: \"FTPS\", database_name: None }] } }'",
            "    at PrismaClientFetcher.request (C:\\Git\\VSTS\\StateNetApps\\Icefall\\src\\generated\\prisma\\deliverables\\client\\runtime\\index.js:78134:15)",
            "    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
            "    at async Promise.all (index 0)",
            "    at async Promise.all (index 0)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

How do I get enums in the DB to work?

**Comment by fullStackDataSolutions** [comment]
Turns out this was caused by null values in enums. So not an issue with Nexus.
