### ISSUE TITLE
orderByRelation previewFeatures gives an error 

### ISSUE THREAD

**Issue by kanso-git** [graphql-nexus/nexus-plugin-prisma#1063]
I have tried to use  the orderByRelation previewFeatures released in version "@prisma/client": "2.19.0",

```
generator client {
  provider = "prisma-client-js"
  previewFeatures=["orderByRelation"]
}
```

After generating the client ` npx prisma generate` and trying to start the dev server i've got the below issue :

```
Error: Could not find ordering argument for Blog.posts
    at SchemaBuilder.argsFromQueryOrModelField (C:\Users\v_2190\nexus-plugin-prisma\examples\blog\node_modules\nexus-plugin-prisma\src\builder.ts:663:15)
    at SchemaBuilder.determineArgs (C:\Users\v_2190\nexus-plugin-prisma\examples\blog\node_modules\nexus-plugin-prisma\src\builder.ts:602:19)
    at SchemaBuilder.buildArgsFromField (C:\Users\v_2190\nexus-plugin-prisma\examples\blog\node_modules\nexus-plugin-prisma\src\builder.ts:584:17)
    at SchemaBuilder.buildFieldConfig (C:\Users\v_2190\nexus-plugin-prisma\examples\blog\node_modules\nexus-plugin-prisma\src\builder.ts:574:18)
    at Proxy.fieldPublisher (C:\Users\v_2190\nexus-plugin-prisma\examples\blog\node_modules\nexus-plugin-prisma\src\builder.ts:525:34)
    at Object.definition (C:\Users\v_2190\nexus-plugin-prisma\examples\blog\src\schema\types\Blog.ts:10:13)
    at SchemaBuilder.walkOutputType (C:\Users\v_2190\nexus-plugin-prisma\examples\blog\node_modules\nexus\src\builder.ts:1532:9)
    at SchemaBuilder.walkTypes (C:\Users\v_2190\nexus-plugin-prisma\examples\blog\node_modules\nexus\src\builder.ts:634:16)
    at SchemaBuilder.getFinalTypeMap (C:\Users\v_2190\nexus-plugin-prisma\examples\blog\node_modules\nexus\src\builder.ts:804:10)
    at makeSchemaInternal (C:\Users\v_2190\nexus-plugin-prisma\examples\blog\node_modules\nexus\src\builder.ts:1662:92)
[ERROR] 10:25:33 Error: Could not find ordering argument for Blog.posts
```
Many thanks in advance

**Comment by nhuesmann** [comment]
This prevented me from upgrading as well.

**Comment by airidasj** [comment]
Please fix this. Because it is hard to model project architecture, knowing that this is a feature, but being unable to use it. :) Love your work!
