### ISSUE TITLE
Error: Could not find filtering argument

### ISSUE THREAD

**Issue by Bjoernstjerne** [graphql-nexus/nexus-plugin-prisma#354]
I do not see my fault :-(

Error:

```
[INFO] 12:35:01 Restarting: /Users/DC-BT/Documents/Projects/necom/server/src/api/Customer/Gift.ts has been modified
Using ts-node version 8.3.0, typescript version 3.5.2
Error: Could not find filtering argument for Gift.categories
    at NexusPrismaBuilder.argsForQueryOrModelField (/Users/DC-BT/Documents/Projects/necom/server/node_modules/@generated/nexus-prisma/index.js:444:23)
    at NexusPrismaBuilder.computeArgsFromField (/Users/DC-BT/Documents/Projects/necom/server/node_modules/@generated/nexus-prisma/index.js:434:25)
    at Object.acc.<computed> [as categories] (/Users/DC-BT/Documents/Projects/necom/server/node_modules/@generated/nexus-prisma/index.js:568:139)
    at Object.definition (/Users/DC-BT/Documents/Projects/necom/server/src/api/Customer/Gift.ts:13:17)
    at SchemaBuilder.walkOutputType (/Users/DC-BT/Documents/Projects/necom/server/node_modules/@prisma/nexus/src/builder.ts:1192:9)
    at SchemaBuilder.walkTypes (/Users/DC-BT/Documents/Projects/necom/server/node_modules/@prisma/nexus/src/builder.ts:456:16)
    at SchemaBuilder.getFinalTypeMap (/Users/DC-BT/Documents/Projects/necom/server/node_modules/@prisma/nexus/src/builder.ts:464:10)
    at buildTypes (/Users/DC-BT/Documents/Projects/necom/server/node_modules/@prisma/nexus/src/builder.ts:1313:18)
    at makeSchemaInternal (/Users/DC-BT/Documents/Projects/necom/server/node_modules/@prisma/nexus/src/builder.ts:1357:9)
    at Object.makeSchema (/Users/DC-BT/Documents/Projects/necom/server/node_modules/@prisma/nexus/src/builder.ts:1408:9)
[ERROR] 12:35:06 Error: Could not find filtering argument for Gift.categories
```

Gift.ts:
```
import { objectType } from 'nexus';
import { queries, QueryMethod } from './';

queries.push({ name: "Gift", methods: [QueryMethod.One, QueryMethod.Many] });

export const Gift = objectType({
    name: 'Gift',
    definition(t) {
        t.model.id()
        t.model.name()
        t.model.cost()
        t.model.path()
        t.model.categories({ 
            filtering: { id: true, name: true }
        })
    },
});
```

GifftCategory.ts:

```
import { objectType } from 'nexus';
import { queries, QueryMethod } from './';

queries.push({ name: "GiftCategory", methods: [QueryMethod.Many, QueryMethod.One] });

export const GiftCategory = objectType({
    name: 'GiftCategory',
    definition(t) {
        t.model.id()
        t.model.name()
        t.model.gifts()
    },
});
```

**Comment by iherger** [comment]
This doesn't seem to be fixed with `prisma2@2.0.0-alpha.130`, `nexus-prisma@0.0.1-beta.6` and `nexus@0.12.0-beta.7`

**Comment by jasonkuhrt** [comment]
Thanks @iherger will take another look

**Comment by 5achinJani** [comment]
@jasonkuhrt 
This two issues also needs to be transferred here and maybe close as duplicate?
https://github.com/prisma/nexus/issues/202
https://github.com/prisma/nexus/issues/203
Maybe this one too :
https://github.com/prisma/nexus-prisma/issues/345

**Comment by hugohammarstrom** [comment]
After updating to the latest preview(prisma2@2.0.0-preview-9) version i get the following error:

```
TypeError: nexus_1.dynamicOutputProperty is not a function
    at NexusPrismaBuilder.getCRUDDynamicOutputMethod (/Users/hugohammarstrom/repos/stateless.digital/wdn/cdn/backend/wdn-prisma/node_modules/@generated/nexus-prisma/index.js:877:24)
    at NexusPrismaBuilder.getNexusPrismaMethod (/Users/hugohammarstrom/repos/stateless.digital/wdn/cdn/backend/wdn-prisma/node_modules/@generated/nexus-prisma/index.js:867:18)
    at Object.nexusPrismaPlugin (/Users/hugohammarstrom/repos/stateless.digital/wdn/cdn/backend/wdn-prisma/node_modules/@generated/nexus-prisma/index.js:1185:20)
    at Object.<anonymous> (/Users/hugohammarstrom/repos/stateless.digital/wdn/cdn/backend/wdn-prisma/src/index.ts:15:21)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Module._compile (/Users/hugohammarstrom/repos/stateless.digital/wdn/cdn/backend/wdn-prisma/node_modules/source-map-support/source-map-support.js:521:25)
    at Module.m._compile (/private/var/folders/hy/2d2222v94qz396wdmlshwvph0000gn/T/ts-node-dev-hook-8353669174630247.js:56:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at require.extensions.(anonymous function) (/private/var/folders/hy/2d2222v94qz396wdmlshwvph0000gn/T/ts-node-dev-hook-8353669174630247.js:58:14)
    at Object.nodeDevHook [as .ts] (/Users/hugohammarstrom/repos/stateless.digital/wdn/cdn/backend/wdn-prisma/node_modules/ts-node-dev/lib/hook.js:61:7)
[ERROR] 09:58:50 TypeError: nexus_1.dynamicOutputProperty is not a function
```

**Comment by jasonkuhrt** [comment]
I enhanced the example to serve as a reference for how filtering is working.
