### ISSUE TITLE
Prisma 2 "GraphQL starter kits" are broken

### ISSUE THREAD

**Issue by nikolasburk** [graphql-nexus/nexus-plugin-prisma#371]
The `graphql` and `graphql-auth` examples both seem to be broken with what appears to be an issue with Nexus, or `nexus-prisma`.

This can be reproduced by following the instructions in both READMES:

- https://github.com/prisma/prisma-examples/tree/prisma2/typescript/graphql-auth
https://github.com/prisma/prisma-examples/tree/prisma2/typescript/graphql

After I followed the instructions and started the GraphQL server, I'm seeing this output:

```
$ npm run start
                              

> typescript-graphql@ start /Users/nikolasburk/Desktop/prisma-examples/typescript/graphql
> ts-node-dev --no-notify --respawn --transpileOnly ./src

Using ts-node version 8.3.0, typescript version 3.6.2
TypeError: nexus_1.dynamicOutputProperty is not a function
    at NexusPrismaBuilder.getCRUDDynamicOutputMethod (/Users/nikolasburk/Desktop/prisma-examples/typescript/graphql/node_modules/@generated/nexus-prisma/index.js:877:24)
    at NexusPrismaBuilder.getNexusPrismaMethod (/Users/nikolasburk/Desktop/prisma-examples/typescript/graphql/node_modules/@generated/nexus-prisma/index.js:867:18)
    at Object.nexusPrismaPlugin (/Users/nikolasburk/Desktop/prisma-examples/typescript/graphql/node_modules/@generated/nexus-prisma/index.js:1185:20)
    at Object.<anonymous> (/Users/nikolasburk/Desktop/prisma-examples/typescript/graphql/src/index.ts:10:21)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Module._compile (/Users/nikolasburk/Desktop/prisma-examples/typescript/graphql/node_modules/source-map-support/source-map-support.js:521:25)
    at Module.m._compile (/private/var/folders/sy/wzhm36711zs2jwz7kzc86z3h0000gn/T/ts-node-dev-hook-1684765961034711.js:56:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at require.extensions.<computed> (/private/var/folders/sy/wzhm36711zs2jwz7kzc86z3h0000gn/T/ts-node-dev-hook-1684765961034711.js:58:14)
    at Object.nodeDevHook [as .ts] (/Users/nikolasburk/Desktop/prisma-examples/typescript/graphql/node_modules/ts-node-dev/lib/hook.js:61:7)
[ERROR] 14:33:01 TypeError: nexus_1.dynamicOutputProperty is not a function
```

**Comment by malekjaroslav** [comment]
Related https://github.com/prisma/nexus-prisma/issues/372
