### ISSUE TITLE
Cannot pass `null` for `orderBy`

### ISSUE THREAD

**Issue by sameoldmadness** [graphql-nexus/nexus-plugin-prisma#457]
Given Prisma 2 schema

```groovy

model Merchant {
  id         String    @default(cuid()) @id
  hostname   String    @unique
}
```

and Nexus config

```typescript
import { extendType } from 'nexus'

export const Query = extendType({
  type: 'Query',
  definition(t) {
    t.crud.merchants({
      ordering: { hostname: true },
    })
  },
})
```

I want to fetch merchants without order

```
query {
  merchants(
    orderBy: null,
  ) {
    id
    hostname
  }
}
```

Instead of valid response, I see an error

```json
{
      "message": "Cannot read property 'id' of null",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "merchants"
      ]
    }
```

`null` value is valid for `first`, `skip` and `where` parameter. So I suppose this is a bug.

**Comment by jasonkuhrt** [comment]
Hey @sameoldmadness that error seems to me more like you received a `null` list member from the server violating its own schema.

**Comment by jasonkuhrt** [comment]
Confirmed in nexus-prisma example app:

```graphql
query a {
  posts (orderBy: null) {
    id
  }
}
```

**Comment by jasonkuhrt** [comment]
Looking at the stack trace, it seems to be photon related:

```
TypeError: Cannot read property 'id' of null
    at Document.normalizePath (/Users/jasonkuhrt/projects/prisma/nexus-prisma/examples/blog/node_modules/@generated/photon/runtime/index.js:1780:34)
    at Document.validate (/Users/jasonkuhrt/projects/prisma/nexus-prisma/examples/blog/node_modules/@generated/photon/runtime/index.js:1685:31)
    at PostClient.get _document [as _document] (/Users/jasonkuhrt/projects/prisma/nexus-prisma/examples/blog/node_modules/@generated/photon/index.js:424:22)
    at PostClient.then (/Users/jasonkuhrt/projects/prisma/nexus-prisma/examples/blog/node_modules/@generated/photon/index.js:445:63)
    at whenResultIsFinished (/Users/jasonkuhrt/projects/prisma/nexus-prisma/examples/blog/node_modules/graphql-extensions/src/index.ts:171:12)
    at field.resolve (/Users/jasonkuhrt/projects/prisma/nexus-prisma/examples/blog/node_modules/graphql-extensions/src/index.ts:156:7)
    at resolveFieldValueOrError (/Users/jasonkuhrt/projects/prisma/nexus-prisma/examples/blog/node_modules/graphql/execution/execute.js:467:18)
    at resolveField (/Users/jasonkuhrt/projects/prisma/nexus-prisma/examples/blog/node_modules/graphql/execution/execute.js:434:16)
    at executeFields (/Users/jasonkuhrt/projects/prisma/nexus-prisma/examples/blog/node_modules/graphql/execution/execute.js:275:18)
    at executeOperation (/Users/jasonkuhrt/projects/prisma/nexus-prisma/examples/blog/node_modules/graphql/execution/execute.js:219:122)
```

**Comment by jasonkuhrt** [comment]
Another way to break things:

```graphql
query a {
  posts (orderBy: {id:null}) {
    id
    title
  }
}
```
```json
{
  "data": null,
  "errors": [
    {
      "message": "Cannot read property 'toString' of null",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "posts"
      ]
    }
  ]
}
```

More details found;

The error from photon comes from validation method of Document:

A snippet:

```js
[
  Arg {
    key: 'orderBy',
    value: Args {
      args: [
        Arg {
          key: 'id',
          value: undefined,
          argType: undefined,
          isEnum: true,
          error: {
            type: 'missingArg',
            missingName: 'id',
            missingType: [
              {
                type: { name: 'OrderByArg', values: [ 'asc', 'desc' ] },
                isList: false,
                isRequired: false,
                kind: 'enum'
              }
            ],
            atLeastOne: true,
            atMostOne: true
          },
          schemaArg: undefined,
          hasError: true
        },
```

~I cannot repro using photon directly, even with something blatantly wrong:~ 🤦‍♂ need `await`

<details>
<summary>outdated</summary>

```js
  // no runtime error
  photon.posts.findMany({
    orderBy: {
      id: 'foo',
    } as any,
    select: {
      id: true,
    },
  })
```

</details>


~Which I do not understand why right now.~

Repro with photon:

```js
  await photon.posts.findMany({ orderBy: null })
```

**Comment by jasonkuhrt** [comment]
I am unable to repro with other args, for example the following works fine:

```graphql
query {
  posts (where:null) {
    id
  }
}
```

**Comment by jasonkuhrt** [comment]
Will leave this issue open for visibility. Will close this once we've upgraded nexus-prisma to depend on a fixed version of photon.

**Comment by jasonkuhrt** [comment]
Blocked by https://github.com/prisma/photonjs/issues/248

**Comment by jasonkuhrt** [comment]
Seems we're still blocked, left a comment on upstream: https://github.com/prisma/prisma-client-js/issues/248#issuecomment-577764308
