### ISSUE TITLE
Use proxies to avoid not defined error blocking compile

### ISSUE THREAD

**Issue by jasonkuhrt** [graphql-nexus/nexus-plugin-prisma#472]
Analogy: Unused variable as error prevents build. At dev time this is annoying because an unused variable may just be a temporary state while working towards some idea, refactor, etc. It is much better at dev time to have this feedback at the level of just a warning, that does not block the compiler from building your code.

The idea is to implement the `t.model` operation publishers and `t.crud` field projectors as proxies so that when there is a sync issue or typo TS compile can still succeed. With proxies we can:

- Provide custom error messages when the field doesn't exist (`please sync` etc.)
- never get in the way of TS compiling, a golden rule

We may want a prod mode where proxies aren't used.

**Comment by Weakky** [comment]
**Currently blocked**
Reason: Errors are printed twice because nexus runs dynamics twice (hence the `needs/upstream` label)

Will affect #479

**Comment by jasonkuhrt** [comment]
Here is an example of the current frustration:

1. I am trying to build the app but get this error:

    ```
    /Users/jasonkuhrt/projects/prisma-labs/nexus-prisma/examples/blog/src/schema/Query.ts:5
        t.crud.blogs({
              ^
    TypeError: t.crud.blogs is not a function
        at Object.definition (/Users/jasonkuhrt/projects/prisma-labs/nexus-prisma/examples/blog/src/schema/Query.ts:5:12)
        at SchemaBuilder.walkOutputType (/Users/jasonkuhrt/projects/prisma-labs/nexus-prisma/examples/blog/node_modules/nexus/src/builder.ts:1441:9)
        at SchemaBuilder.walkTypes (/Users/jasonkuhrt/projects/prisma-labs/nexus-prisma/examples/blog/node_modules/nexus/src/builder.ts:681:16)
        at SchemaBuilder.getFinalTypeMap (/Users/jasonkuhrt/projects/prisma-labs/nexus-prisma/examples/blog/node_modules/nexus/src/builder.ts:780:10)
        at makeSchemaInternal (/Users/jasonkuhrt/projects/prisma-labs/nexus-prisma/examples/blog/node_modules/nexus/src/builder.ts:1565:15)
        at Object.makeSchema (/Users/jasonkuhrt/projects/prisma-labs/nexus-prisma/examples/blog/node_modules/nexus/src/builder.ts:1610:49)
        at Object.<anonymous> (/Users/jasonkuhrt/projects/prisma-labs/nexus-prisma/examples/blog/src/schema/index.ts:10:22)
        at Module._compile (internal/modules/cjs/loader.js:956:30)
        at Module.m._compile (/Users/jasonkuhrt/projects/prisma-labs/nexus-prisma/examples/blog/node_modules/ts-node/src/index.ts:493:23)
        at Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    error Command failed with exit code 1.
    ```

2. So I go to the source code to see what's up

    ![image](https://user-images.githubusercontent.com/284476/68426110-72f9db00-0175-11ea-96fd-08a99413e8e5.png)

3. Sure enough, right, the static error. But now what? I want to know what are the  actually available types. To achieve that, I need typegen, but I cannot produce typegen because of the type error...

**Comment by IzioDev** [comment]
@jasonkuhrt Any workaround for this?

**Comment by jasonkuhrt** [comment]
@izio38 the work around for now is fix all errors before continuing.

**Comment by IzioDev** [comment]
> @izio38 the work around for now is fix all errors before continuing.

I'm sorry, but I can't understand what errors needs to be fix. For some reason, the compilation just doesn't pass and I'm not able to see what else is wrong.
If there is no other way than commenting the `t.model` stuff it's fine, I'll do it :)

Thanks for the quick answer.

**Comment by jasonkuhrt** [comment]
@izio38 Try commenting out all the errors, then incrementally bring them back and debug one by one.

**Comment by Weakky** [comment]
> the work around for now is fix all errors before continuing

I'm not sure I agree here? These are TypeScript errors. The "workaround" is just to run the server with `ts-node --transpile-only` or `ts-node-dev --transpileOnly` 🤔?

**Comment by jasonkuhrt** [comment]
@Weakky right you are
