### ISSUE TITLE
Crashes on Heroku Postgres Database

### ISSUE THREAD

**Issue by jlarmstrongiv** [graphql-nexus/nexus-plugin-prisma#561]
After updating dependencies and adding a Heroku postgres datasource, the example no longer worked.  If I install a local postgres database and connect to it, then everything is peachy.

```
> hello-world@1.0.0 start /Users/jlarmst/Downloads/boombox-v3
> ts-node --transpile-only app

🚀 GraphQL service ready at http://localhost:4000
Error:
Invalid `photon.()` invocation in /Users/jlarmst/Downloads/boombox-v3/node_modules/nexus-prisma/src/builder.ts:238:18



undefined target="exit" timestamp="2019-12-15T03:45:31.419Z" fields={"message":"1"}
    at PhotonFetcher.<anonymous> (/Users/jlarmst/Downloads/boombox-v3/node_modules/@prisma/photon/index.js:65:27)
    at Generator.throw (<anonymous>)
    at rejected (/Users/jlarmst/Downloads/boombox-v3/node_modules/@prisma/photon/index.js:6:65)
^C
```

**Comment by StphnRssll** [comment]
I also had problems connecting to Heroku
```
node ./script.js

Error:
Invalid `const user1 = await photon.users.create()` invocation in C:\Users\sonic\Documents\Coding\traceLab\winterCamp19\prismaTutorial\script.js:7:36

   3
   4 // A `main` function so that we can use async/await
   5 async function main() {
   6   // Seed the database with users and posts
→  7   const user1 = await photon.users.create(

undefined target="exit" timestamp="2019-12-15T04:21:14.340Z" fields={"message":"1"}
    at PhotonFetcher.<anonymous> (C:\Users\sonic\Documents\Coding\traceLab\winterCamp19\prismaTutorial\node_modules\@prisma\photon\index.js:65:27)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\sonic\Documents\Coding\traceLab\winterCamp19\prismaTutorial\node_modules\@prisma\photon\index.js:6:65)
(node:17964) UnhandledPromiseRejectionWarning: Error: undefined target="exit" timestamp="2019-12-15T04:21:14.340Z" fields={"message":"1"}
    at NodeEngine.engineReady (C:\Users\sonic\Documents\Coding\traceLab\winterCamp19\prismaTutorial\node_modules\@prisma\photon\runtime\index.js:3533:23)
    at async C:\Users\sonic\Documents\Coding\traceLab\winterCamp19\prismaTutorial\node_modules\@prisma\photon\runtime\index.js:3456:21
(node:17964) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17964) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jlarmstrongiv** [comment]
The heroku connection works if you hard code it and don’t use env()

This issue may be a better fit in the prisma2 repo

**Comment by jlarmstrongiv** [comment]
Issue tracked on prisma2 github 
https://github.com/prisma/photonjs/issues/305
