### ISSUE TITLE
Plural mapping error

### ISSUE THREAD

**Issue by impowski** [graphql-nexus/nexus-plugin-prisma#581]
I just switched to latest `prisma2` and I keep getting this errors no idea why, all of my code was fixed properly. I guess something wrong inside `nexus-prisma` implementation regarding plural mapping.

```console
Error: "prisma.users" has been renamed to "prisma.user"
    at PrismaClient.get users [as users] (../node_modules/@prisma/client/index.js:302:15)
    at fieldConfig.buildFieldConfig.resolve.field.outputType.kind.object (../node_modules/nexus-prisma/src/builder.ts:467:32)
    at middleware (../node_modules/graphql-middleware/src/applicator.ts:34:9)
    at middleware (../node_modules/graphql-shield/src/generator.ts:70:16)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

**Comment by impowski** [comment]
@Weakky can you take a look at this one please?

**Comment by impowski** [comment]
They reverted it back in `prisma2-preview020.3` so now it works fine

**Comment by impowski** [comment]
But the latest alpha doesn't work so I suppose should be fixed

**Comment by Weakky** [comment]
Hey @impowski,

Thanks for raising that issue. I can confirm the problem. We need to wait for the official release to support that

**Comment by jasonkuhrt** [comment]
0.9.1 nexus-Prisma  and Prisma preview 21 are available now.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
