### ISSUE TITLE
ReferenceError: message is not defined at PrismaClientFetcher.request

### ISSUE THREAD

**Issue by cdub615** [graphql-nexus/nexus-plugin-prisma#623]
I'm getting this reference error when running my api in Google Cloud Functions (I'm using apollo-server-cloud-functions), and I'm struggling to identify the root cause.

I don't get this when running the api locally with the Functions Framework which emulates the serverless environment.

I've had to generate the Prisma Client in a project folder and specify nexus output in a project folder as well because Google Cloud Functions was giving me directory read-only errors when trying to run prisma generate in the build. Everything else is pretty straightforward though, my Types are all generated from create-nexus-type.

Can someone help me find out more about what's going wrong? Please let me know what more info may be needed!

Here's the error I'm getting:
```code
{
  "errors": [
    {
      "message": "message is not defined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "clients"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "ReferenceError: message is not defined",
            "    at PrismaClientFetcher.request (/srv/api/prisma-client/index.js:106:76)",
            "    at <anonymous>",
            "    at process._tickDomainCallback (internal/process/next_tick.js:229:7)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

This is my schema configuration and server:
#### schema.js
```code
const path = require('path');
const { makeSchema } = require('nexus');
const { nexusPrismaPlugin } = require('nexus-prisma');
const Types = require('./types/types');

exports.schema = makeSchema({
  types: [Types],
  plugins: [
    nexusPrismaPlugin({
      shouldGenerateArtifacts: process.env.NODE_ENV === 'local',
      inputs: { prismaClient: path.join(__dirname, './prisma-client') },
      outputs: {
        typegen: path.join(__dirname, './nexus-typegen/nexus-typegen.d.ts'),
      },
    }),
  ],
  shouldGenerateArtifacts: process.env.NODE_ENV === 'local',
  outputs: {
    typegen: path.join(__dirname, './nexus-typegen/index.d.ts'),
  },
});
```

#### serverlessApi.js
```code
const { ApolloServer } = require('apollo-server-cloud-functions');
const { PrismaClient } = require('../api/prisma-client/index');
const { schema } = require('../api/schema');

const prisma = new PrismaClient();

const server = new ApolloServer({
  schema,
  context: ({ req, res }) => ({
    headers: req.headers,
    req,
    res,
    prisma,
  }),
  playground: true,
  introspection: true,
  tracing: true,
  debug: true,
});

const options = {
  cors: {
    origin: true,
    credentials: true,
  },
};

exports.serverlessApi = server.createHandler(options);

```

**Comment by cdub615** [comment]
I realized since I was using the pre-generated prisma client I could add some logs around the location where the error was occurring, and I received the following information:

> Error: Query engine binary for current platform "debian-openssl-1.1.x" could not be found. This probably happens, because you built Prisma Client on a different platform. (Prisma Client looked in "/srv/api/prisma-client/runtime/query-engine-debian-openssl-1.1.x") To solve this problem, add the platform "debian-openssl-1.1.x" to the "generator" block in the "schema.prisma" file: generator client { provider = "prisma-client-js" binaryTargets = ["native"] } Then run "prisma2 generate" for your changes to take effect. Read more about deploying Prisma Client: https://pris.ly/d/client-generator

I added the binaryTargets parameter to the generator block of my schema.prisma file with native and the missing debian target and that did the trick!

```code
generator client {
    provider      = "prisma-client-js"
    output        = "../prisma-client"
    binaryTargets = ["native", "debian-openssl-1.1.x"]
}
```
