### ISSUE TITLE
Could not find schema arg with name: 0 "nexus-prisma": "^0.15.0-next.6",

### ISSUE THREAD

**Issue by Bjoernstjerne** [graphql-nexus/nexus-plugin-prisma#713]
In the latest version this query:
```
query getConversations($userId: String){
    conversations {
        conversations{
            id,
            profiles(where: {NOT: [{profile: {id: {equals: $userId}}}]}) {
                profile {
                    id,
                    profileName
                    images(where: {main: {equals: true}}){
                        path
                    }
                }
            }
            messages {
                id,
            }
        }
        count
    }
}
```

results in this error:

```

      "message": "Could not find schema arg with name: 0",
      "locations": [
        {
          "line": 5,
          "column": 7
        }
      ],
      "path": [
        "conversations",
        "conversations",
        0,
        "profiles"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Could not find schema arg with name: 0",
            "    at transformNullsToUndefined (/c/Users/bjoer/Documents/Projects/necom/node_modules/nexus-prisma/src/null.ts:24:13)",
            "    at transformNullsToUndefined (/c/Users/bjoer/Documents/Projects/necom/node_modules/nexus-prisma/src/null.ts:34:26)",
            "    at Object.transformNullsToUndefined (/c/Users/bjoer/Documents/Projects/necom/node_modules/nexus-prisma/src/null.ts:34:26)",
            "    at originalResolve (/c/Users/bjoer/Documents/Projects/necom/node_modules/nexus-prisma/src/builder.ts:498:24)",
            "    at /c/Users/bjoer/Documents/Projects/necom/node_modules/graphql-middleware/src/applicator.ts:34:9",
            "    at middleware (/c/Users/bjoer/Documents/Projects/necom/node_modules/graphql-shield/src/generator.ts:70:16)",
            "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
          ]
        }
      }
    }
  ],
  "data": {
    "conversations": {
      "conversations": null,
      "count": 3
    }
  }
}
```

I use nexusPrismaPlugin with 
```
            experimentalCRUD: true,
            paginationStrategy: 'prisma',
```
The nexus object is:
```
export const ConversationI = interfaceType({
    name: 'ConversationI',
    definition: (t) => {
        t.model('Conversation').id();
        t.model('Conversation').profiles({ filtering: true });
        /*
        t.field('messages', {
            nullable: true,
            list: [true],
            type: 'Message',
            args: {
                where: 'MessageWhereInput',
                orderBy: 'MessageOrderByInput',
                cursor: 'MessageWhereUniqueInput',
                take: 'Int',
                skip: 'Int',
            },
        });
        */
        t.model('Conversation').messages({
            filtering: true,
            ordering: true,
            pagination: true,
        });
        t.resolveType(() => {
            return 'Conversation';
        });
    },
});

```
The removed lines are working with version "^0.14.0"

**Comment by oceandrama** [comment]
@jasonkuhrt can confirm it too with version `0.15.0` Any updates?

**Comment by aarshaw** [comment]
Also having this issue in `0.15.0` > for me it happens with the `NOT` filter included, works without

**Comment by aarshaw** [comment]
In the above example I get the impression this `profiles(where:{profile: {id: {not: $userId}}}) {` would work.

In our case, because the filter is an `ENUM` - the above isn't an option
