### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by mark-antony1** [graphql-nexus/nexus-plugin-prisma#976]
Hello,

I am trying to run nexus-plugin-prisma with the newest version of prisma2, version  2.12.1   and I am getting the following error when trying to run my local server.

```
TypeError: Cannot read property 'map' of undefined
    at transformSchema (/Users/jchri/repos/together-web/node_modules/nexus-plugin-prisma/dist/dmmf/transformer.js:36:39)
    at transform (/Users/jchri/repos/together-web/node_modules/nexus-plugin-prisma/dist/dmmf/transformer.js:22:17)
    at Object.exports.getTransformedDmmf (/Users/jchri/repos/together-web/node_modules/nexus-plugin-prisma/dist/dmmf/transformer.js:16:100)
    at new SchemaBuilder (/Users/jchri/repos/together-web/node_modules/nexus-plugin-prisma/dist/builder.js:136:24)
    at Object.build (/Users/jchri/repos/together-web/node_modules/nexus-plugin-prisma/dist/builder.js:76:21)
    at Object.onInstall (/Users/jchri/repos/together-web/node_modules/nexus-plugin-prisma/dist/plugin.js:47:78)
    at /Users/jchri/repos/together-web/node_modules/@nexus/schema/dist/builder.js:319:52
    at Array.forEach (<anonymous>)
    at SchemaBuilder.beforeWalkTypes (/Users/jchri/repos/together-web/node_modules/@nexus/schema/dist/builder.js:312:22)
    at SchemaBuilder.getFinalTypeMap (/Users/jchri/repos/together-web/node_modules/@nexus/schema/dist/builder.js:455:14)
TypeError: Cannot read property 'map' of undefined
    at transformSchema (/Users/jchri/repos/together-web/node_modules/nexus-plugin-prisma/dist/dmmf/transformer.js:36:39)
    at transform (/Users/jchri/repos/together-web/node_modules/nexus-plugin-prisma/dist/dmmf/transformer.js:22:17)
    at Object.exports.getTransformedDmmf (/Users/jchri/repos/together-web/node_modules/nexus-plugin-prisma/dist/dmmf/transformer.js:16:100)
    at new SchemaBuilder (/Users/jchri/repos/together-web/node_modules/nexus-plugin-prisma/dist/builder.js:136:24)
    at Object.build (/Users/jchri/repos/together-web/node_modules/nexus-plugin-prisma/dist/builder.js:76:21)
    at Object.onInstall (/Users/jchri/repos/together-web/node_modules/nexus-plugin-prisma/dist/plugin.js:47:78)
    at /Users/jchri/repos/together-web/node_modules/@nexus/schema/dist/builder.js:319:52
    at Array.forEach (<anonymous>)
    at SchemaBuilder.beforeWalkTypes (/Users/jchri/repos/together-web/node_modules/@nexus/schema/dist/builder.js:312:22)
    at SchemaBuilder.getFinalTypeMap (/Users/jchri/repos/together-web/node_modules/@nexus/schema/dist/builder.js:455:14)
```

I did not get this error when I was running prisma version 2.11.0, does anybody have familiarity with this bug? @jasonkuhrt @tgriesser

**Comment by mark-antony1** [comment]
Closing as it relates to updating Nexus-plugin-prisma to version 0.25, but this would be nice to have it publicized in the docs, or somewhere else.
